services:
  n8n:
    image: n8nio/n8n:2.20.6
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data: